---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor.dhaka.cf-app.com/srp/srp-helper-task 
    username: ((srp-cli-registry-creds.username))
    password: ((srp-cli-registry-creds.password))

inputs:
- name: docs-platform-automation
- name: concourse-build-info
- name: srp-data
- name: version

outputs:

params:
  CLIENT_ID:  
  CLIENT_SECRET:
  DOMAIN:

run:
  path: docs-platform-automation/ci/tasks/srp-init/task
