FROM internalpcfplatformautomation/platform-automation:packages

# remove azure cli
RUN pip3 install pip-autoremove setuptools
RUN pip-autoremove -y azure-cli

# remove pip
RUN pip3 uninstall -y pip-autoremove setuptools pip

# remove gcloud CLI
RUN rm -Rf /usr/local/bin/gcloud
RUN rm -Rf /root/google-cloud-sdk
