# syntax=docker/dockerfile:1.4
ARG base_image
FROM ${base_image}

ARG PIP_INDEX_URL_BASE=""

# remove azure cli
RUN --mount=type=secret,id=artifactory_user,dst=/run/secrets/artifactory_user \
    --mount=type=secret,id=artifactory_pass,dst=/run/secrets/artifactory_pass \
    if [ -s /run/secrets/artifactory_user ] && [ -s /run/secrets/artifactory_pass ] && [ -n "$PIP_INDEX_URL_BASE" ]; then \
        export PIP_INDEX_URL="https://$(cat /run/secrets/artifactory_user):$(cat /run/secrets/artifactory_pass)@${PIP_INDEX_URL_BASE}"; \
    fi && \
    pip3 install pip-autoremove
RUN pip-autoremove -y azure-cli

# remove AWS CLI
RUN pip-autoremove -y awscli

# remove Openstack CLI
RUN pip-autoremove -y python-openstackclient

# remove pip
RUN pip3 uninstall -y pip-autoremove pip

# remove gcloud CLI
RUN rm -Rf /usr/local/bin/gcloud
RUN rm -Rf /root/google-cloud-sdk

RUN rm -Rf /usr/lib/python*
RUN rm -Rf /usr/bin/python*
RUN rm -Rf /usr/local/lib/python*
RUN rm -Rf /usr/local/bin/python*
RUN rm -Rf /etc/python*
