FROM internalpcfplatformautomation/platform-automation:packages

# remove azure cli and pip
# pip-autoremove is incompatible with Python 3.12
RUN pip3 uninstall -y azure-cli pip

# remove gcloud CLI
RUN rm -Rf /usr/local/bin/gcloud
RUN rm -Rf /root/google-cloud-sdk
