ARG base_image=tas-operability-docker-virtual.usw1.packages.broadcom.com/golang:1.15
FROM ${base_image}

RUN git clone https://github.com/pivotal-cf/om
RUN cd om && go build -o /usr/bin/om main.go
RUN apt-get update && \
    apt-get -y install gettext-base && \
    apt-get clean
