---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing

inputs:
- name: docs-platform-automation
outputs:
- name: docs-platform-automation

run:
  path: bash
  args:
  - -c
  - |
    set -eux
    pushd docs-platform-automation
      cat /dev/null > ci/patch-notes/cve-patch-notes.md
      if [[ -n $(git status --porcelain) ]]; then
        git add -A
        git commit -m "remove documented shared release notes"
      fi
    popd
