---
platform: linux
inputs:
- name: platform-automation-tasks
- name: windows-iso
  optional: true
outputs:
- name: logs
- name: stemcell
params:
  # Set to "true" to enable set -x for build.sh and all child scripts (or pass from pipeline task params)
  DEBUG_MODE: "false"
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/platform-automation
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
    tag: testing
run:
  path: platform-automation-tasks/tasks/build-windows-stemcell.sh
