# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet configure-opsman start yaml
---
platform: linux

inputs:
  - name: platform-automation-tasks
  - name: config # contains the OpsMan configuration file
  - name: env # contains the environment information for OpsMan
  - name: vars # variable files to be made available
    optional: true
  - name: secrets # secret files to be made available
    # separate from vars, so they can be stored securely
    optional: true

params:
  VARS_FILES:
  # - Optional
  # - space-separated array of filepaths to YAML vars files
  #   to be loaded with the CONFIG_FILE
  # - relative to root of the task build,
  #   so both `vars` and `secrets` can be used.

  ENV_FILE: env.yml
  # - Required
  # - filepath of the env config YAML
  # - relative to root of the `env` input

  OPSMAN_CONFIG_FILE: opsman.yml
  # - Required
  # - filepath of the Ops Manager Application Settings
  #   config file. (such as banner, pivnet token, etc)
  # - relative to root of the `config` input
  # - It is recommended to use one config file to
  #   configure-opsman, upgrade-opsman, create-vm, delete-vm

run:
  path: platform-automation-tasks/tasks/configure-opsman.sh
# code_snippet configure-opsman end
