# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet create-certificate-authority start yaml
---
platform: linux

inputs:
- name: platform-automation-tasks
- name: env # contains the env file with target OpsMan Information
- name: certs # contains the cert and private key for the CA
  # certs/certificate.pem and certs/privatekey.pem will be in inside the certs folder

params:
  ENV_FILE: env.yml
  # - Required
  # - Filepath of the env config YAML

run:
  path: platform-automation-tasks/tasks/create-certificate-authority.sh
# code_snippet create-certificate-authority end