# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet expiring-licenses start yaml
---
platform: linux

inputs:
  - name: platform-automation-tasks

params:
  ENV_FILE: env.yml
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

  EXPIRES_WITHIN:
  # - Optional
  # - Example: "3m" is 3 months
  # - Check for licenses expiring within the defined time period
  # - Supports a time period defined with a suffix of:
  #   days(d), weeks(w), months(m) and years(y)
  # - Defaults to "3m" if not specified

  STAGED:
  # - Optional
  # - Boolean flag
  # - Include staged products in the check
  # - Defaults to false if not specified

  DEPLOYED:
  # - Optional
  # - Boolean flag
  # - Include deployed products in the check
  # - Defaults to false if not specified

run:
  path: platform-automation-tasks/tasks/expiring-licenses.sh
# code_snippet expiring-licenses end
