# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet prepare-tasks-with-secrets start yaml
---
platform: linux

inputs:
  - name: platform-automation-tasks
  - name: tasks
    # Contains the task files that will be modified to contain secrets
    # as environment variables
  - name: config
    # Contains the config files with (()) parameterized variables
  - name: vars
    # Optional input for variables to be made available for use with VARS_PATHS
    # - See the VARS_PATHS param for more information
    optional: true

outputs:
  - name: tasks
    # contains the modified tasks

params:
  CONFIG_PATHS: config
  # - Optional
  # - Paths of the directories containing the config files
  # - The path is relative to root of the task build
  # - Child folders will be recursively searched

  VARS_PATHS:
  # - Optional
  # - Variables found under files in VARS_PATHS
  #   will not be added to tasks for lookup
  #   from Concourse's credential manager.
  #   If VARS_FILES are used in later tasks,
  #   they must be accounted for here to avoid task setup failure.
  # - If VARS_PATH is not set and the vars input is provided,
  #   VARS_PATH will be set to the root of the vars input
  # - The path is relative to root of the task build
  # - Child folders will be recursively searched
  # - Multiple paths can be provided separated by spaces

run:
  path: platform-automation-tasks/tasks/prepare-tasks-with-secrets.sh
# code_snippet prepare-tasks-with-secrets end
