---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: packaged-product

params:
  PRODUCT_PATH: platform-automation-image-*.tgz

run:
  path: bash
  args:
    - -c
    - |

      set -eu

      # shellcheck disable=SC1091
      source /opt/resource/common.sh
      start_docker "5" "5" "" ""

      set -eux

      # shellcheck disable=SC2086
      docker import packaged-product/${PRODUCT_PATH} testing
      docker run testing om --version
