---
platform: linux
inputs:
- name: pas-windows-stemcell-pivnet
- name: docs-platform-automation
outputs:
- name: stemcell
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing
run:
  path: docs-platform-automation/ci/tasks/rename-windows-stemcell/task.rb
