---
platform: linux
inputs:
- name: pas-windows-stemcell-pivnet
- name: docs-platform-automation
outputs:
- name: stemcell
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
run:
  path: docs-platform-automation/ci/tasks/rename-windows-stemcell/task.rb
