---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
inputs:
- name: docs
- name: docs-platform-automation
outputs:
- name: docs
run:
  path: bash
  args:
  - -c
  - |
    set -eux

    cat docs-platform-automation/ci/tasks/docs-nginx-rewrite-rules.conf >> docs/nginx/conf/redirect.conf
