---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ubuntu
inputs:
- name: docs
- name: ci
outputs:
- name: docs
run:
  path: bash
  args:
  - -c
  - |
    set -eux

    cat ci/ci/tasks/docs-nginx-rewrite-rules.conf >> docs/nginx/conf/redirect.conf
