---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))

inputs:
  - name: docs-platform-automation-with-docs

params:
  BLACKDUCK_URL:
  BLACKDUCK_API_TOKEN:
  BLACKDUCK_PROJECT_NAME:
  BLACKDUCK_VERSION:
  BLACKDUCK_PREVIOUS_VERSION:
  DRY_RUN: "false"

run:
  path: python3
  args:
    - docs-platform-automation-with-docs/ci/scripts/blackduck-carry-forward-justifications.py
