---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
- name: docs-platform-automation
outputs:
- name: image
params:
  DOCKERFILE:

run:
  path: build
