---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.url))/vito/oci-build-task
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))

inputs:
- name: docs-platform-automation
outputs:
- name: image
params:
  DOCKERFILE:
  REGISTRY_USERNAME: ((concourse-team/dev_image_registry.username))
  REGISTRY_PASSWORD: ((concourse-team/dev_image_registry.password))
  REGISTRY_URL: ((concourse-team/dev_image_registry.url))
run:
  path: build
