---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.url))/concourse/oci-build-task
    username: ((concourse-team/dev_image_registry.username))                                           
    password: ((concourse-team/dev_image_registry.password))
inputs:
- name: base-image
- name: docs-platform-automation
outputs:
- name: image
params:
  DOCKERFILE:
  IMAGE_ARG_base_image:
run:
  path: build