platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing

inputs:
- name: rc-image-receipt-s3
- name: osl-validated-image-receipt-s3

run:
  path: bash
  args:
  - -c
  - |
    set -eux
    grep ii rc-image-receipt-s3/image-receipt-test | awk '{print $2}' > dpglist
    grep ii osl-validated-image-receipt-s3/image-receipt-* | awk '{print $2}' > dpglistold

    if ! diff dpglist dpglistold ; then
      { echo "A dependency change, as shown above, will prevent OSL reuse.
      If you are willing to go through the OSL process,
      update the validated image input to this task,
      run the NORSK pipelines,
      and submit a new version for OSM validation.
      Remember that this will take at least two weeks.
      If not, see if you can get rid of the dependency change."; } 2> /dev/null

      exit 1
    fi
