platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/buildroot
    tag: curl
run:
  path: bash
  args:
  - -c
  - |
    set -eu

    cat > notification-text/text <<EOF
      Found a secret in a build! See concourse(https://platform-automation.ci.cf-app.com/teams/main/pipelines/ci) for more details.
    EOF
outputs:
- name: notification-text
