platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing
inputs:
- name: docs-platform-automation
caches:
- path: go
run:
  path: bash
  args:
  - -c
  - |
    set -eux

    export GOPATH="$(pwd)/go"
    export PATH="${PATH}:${GOPATH}/bin"

    pushd docs-platform-automation
      ginkgo -r -skip "Generate Release Notes Suite"
    popd
