platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
inputs:
- name: docs-platform-automation
caches:
- path: go
run:
  path: bash
  args:
  - -c
  - |
    set -eux

    export GOPATH="$(pwd)/go"
    export PATH="${PATH}:${GOPATH}/bin"

    pushd docs-platform-automation
      ginkgo -r -skip "Generate Release Notes Suite"
    popd
