platform: linux
run:
  path: bash
  args:
  - -c
  - |
    set -eux
    dpkg -l > rc-image-receipt-s3/image-receipt-"$(cat version/version)"
inputs:
- name: version
outputs:
- name: rc-image-receipt-s3
