---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/source_insight_tooling/osspi-runner

inputs:
  - name: repo1
  - name: repo2
params:
  REPO:
  URL_LIST_FILE:
  API_KEY:
  OSM_ENVIRONMENT: beta
  OSSTP_LOAD_DRY_RUN:
  OSSTP_LOAD_FORCE_LOAD:
  USERNAME:
  PRODUCT:
  VERSION:
run:
  path: repo1/tasks/osspi/run-url-list.sh
