---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))

inputs:
  - name: version
  - name: packaged-product
  - name: tvs-cli
  - name: docs-platform-automation-with-docs

params:
  TAGS:
  BLACKDUCK_PROJECT_URL:
  GITHUB_BRANCH:

run:
  path: docs-platform-automation-with-docs/ci/tasks/scan-and-submit-sboms.sh
