platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing
inputs:
  - name: generated-config
run:
  path: bash
  args:
    - -c
    - |
      cat generated-config/director.yml
