---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ubuntu
params:
  TEST_SPECIAL: ((test))
run:
  path: bash
  args:
  - -c
  - |
    set -eux
    echo "Hello Ryan & Harish"
    echo $TEST_SPECIAL
