platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((concourse-team/dev_image_registry.url))/golang
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
inputs:
  - name: rmt-artifacts
  - name: rmt-release-config
  - name: release-created
  - name: docs-platform-automation
  - name: packaged-product
run:
  path: sh
  args:
    - -exc
    - |
      RELEASE_ID="$(cat release-created/id)"
      
      apt update -y &&\
      DEBIAN_FRONTEND=noninteractive apt install yq -y
      
      cd rmt-artifacts
      cp ../rmt-release-config/pa-release-${VERSION}.yml release.yml
      cat ../rmt-release-config/pa-release-files-${VERSION}.yml >> release.yml
      cat release.yml
      
      ../docs-platform-automation/ci/tasks/check-if-files-present.sh
      
      ./rmt release-update --release-file release.yml --id ${RELEASE_ID}
