#!/bin/bash

cd $1

echo "$BUILD_ID" > build-id
echo "$BUILD_NAME" > build-name
echo "$BUILD_JOB_NAME" > build-job-name
echo "$BUILD_PIPELINE_NAME" > build-pipeline-name
echo "$ATC_EXTERNAL_URL" > atc-external-url
echo "{\"version\":{\"build\":\"$BUILD_ID\"}}"
