---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/docker-image-resource
    tag: 1.8.0-20230816  # Note: pinned on 1/23/24, as this is the last known functional version.  'latest' currently results
                         #       in MANIFEST_BLOB_UNKNOWN errors on TanzuNet Harbor. seems to be an issue with docker
                         #       versions (24.0.5 here vs 25.0.0 in 'latest').  Unpin this when the error stops.  See
                         #       here for details: https://platform-automation.ci.cf-app.com/teams/main/pipelines/ci/jobs/build-binaries-image-combined/builds/2413#L64b8829b:5

inputs:
- name: packaged-product

outputs:
- name: platform-automation-image-oci
- name: vsphere-platform-automation-image-oci

run:
  path: bash
  args:
  - -c
  - |
    set -eu

    # shellcheck disable=SC1091
    source /opt/resource/common.sh
    start_docker "5" "5" "" ""

    set -eux

    export image_sha="$(docker import packaged-product/platform-automation-image-*.tgz)"
    docker save --output platform-automation-image-oci/image.tar $image_sha

    export image_sha="$(docker import packaged-product/vsphere-platform-automation-image-*.tar.gz)"
    docker save --output vsphere-platform-automation-image-oci/image.tar $image_sha
