resources:
- name: docs-platform-automation
  type: git
  source:
    branch: develop
    private_key: ((platform_automation.private_key))
    uri: git@github.com:pivotal/docs-platform-automation
    ignore_paths:
      - docs
- name: image-tanzunet-dev
  type: registry-image
  source:
    repository: dev.registry.pivotal.io/platform-automation/platform-automation-image
    username: ((tanzunet-dev-registry.username))
    password: ((tanzunet-dev-registry.password))
    pre_releases: true
    tag: develop

jobs:
- name: send-rc-to-osm
  plan:
  - get: docs-platform-automation
  - get: image
    resource: image-tanzunet-dev
    params:
      format: oci
  - task: send-to-osm-dev
    file: docs-platform-automation/ci/tasks/run-osspi-docker/task.yml
    params:
      TAR_PATH: image/image.tar
      API_KEY: ((osm.api_key))
      OSM_ENVIRONMENT: beta
      ENDPOINT: https://osm-beta.eng.vmware.com
      USERNAME: ((osm.username))
      PRODUCT: platform-automation
      VERSION: test-platform-automation
      APPEND: true
