resource_types:
  - name: gitlab
    type: registry-image
    source:
      repository: devtools-docker.artifactory.eng.vmware.com/vmware/runway/resourcetypes/gitlab-resource
      tag: 1.0.0
  - name: semver-with-arn
    type: registry-image
    source:
      repository: concourse/semver-resource
      tag: 1.6.0-ubuntu

resources:
  - name: docs-platform-automation
    type: git
    icon: github
    source:
      branch: develop
      uri: git@github.com:pivotal/docs-platform-automation
      private_key: ((platform_automation_docs.private_key))

  - name: om
    type: git
    icon: github
    source:
      uri: git@github.com:pivotal-cf/om.git
      private_key: ((platform_automation_docs.private_key))
      branch: main
      
  - name: rc-image-tanzunet-dev
    type: registry-image
    icon: google-cloud
    source:
      repository: gcr.io/cf-norm-ci/platform-automation/platform-automation-image
      username: _json_key
      password: ((gcr.key_json))
      tag: develop

  - name: norsk-to-osspi
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:source-insight-tooling/norsk-to-osspi.git
      private_key: ((gitlab.private_key))
      branch: main

  - name: version-v5.2
    type: semver-with-arn 
    icon: aws
    source:
      driver: s3
      access_key_id: ((s3_with_role.access_key_id))
      secret_access_key: ((s3_with_role.secret_access_key))
      assume_role_arn: ((s3_with_role.role_arn))
      bucket: ((s3.bucket))
      region_name: ((s3.region_name))
      key: version-v5.2
      initial_version: 0.0.1-rc.1

jobs:
  - name: osm
    serial: true
    plan:
      - in_parallel:
          - get: docs-platform-automation
          - get: om
            params: { submodules: all }
          - get: rc-image-tanzunet-dev
            params:
              format: oci
          - get: version-v5.2
          - get: norsk-to-osspi
      - task: osspi-scan-om
        file: norsk-to-osspi/tasks/osspi/run-osspi-source.yaml
        input_mapping:
          repo1: norsk-to-osspi
          repo2: om
        params:
          OSM_ENVIRONMENT: production
          API_KEY: ((osm.production_api_key))
          USERNAME: ((osm.production_username))
          ENDPOINT: https://osm.eng.vmware.com
          PRODUCT: 'platform-automation'
          VERSION: 'latest'
          REPO: repo2
          OSSTP_LOAD_DRY_RUN: true  
          PREPARE: |
            go mod vendor
          OSSPI_SCANNING_PARAMS: |
            enable: true
            include_bomtools: "go_mod"
            search_depth: 5
            go_mod.path: "/go/bin/go"
          OSSPI_IGNORE_RULES: |
            - name_regex: onsi\/ginkgo
              version_regex: .*
            - name_regex: gomega
              version_regex: .*
      - task: osspi-scan-docker
        file: norsk-to-osspi/tasks/osspi/run-osspi-docker.yaml
        input_mapping:
          repo1: norsk-to-osspi
          image: rc-image-tanzunet-dev
        params:
          OSM_ENVIRONMENT: production
          OSSTP_LOAD_DRY_RUN: true
          API_KEY: ((osm.production_api_key))
          USERNAME: ((osm.production_username))
          ENDPOINT: https://osm.eng.vmware.com
          PRODUCT: platform-automation
          VERSION: latest
          CT_TRACKER_OS: ubuntu
          TAR_PATH: image/image.tar
          TAG: latest
