---
platform: linux
inputs:
- name: deployments
- name: docs-platform-automation
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing
run:
  path: bash
  args:
    - -c
    - |
      set -eux

      pushd docs-platform-automation/ci/tasks/secrets-verifier
        bundle install
      popd
      ./docs-platform-automation/ci/tasks/secrets-verifier/finder.rb
params:
  RUBYOPT: "-E utf-8:utf-8"
