releases:
  - name: os-conf
    version: 22.0.0

addons:
  - name: os-configuration
    jobs:
      - name: login_banner
        release: os-conf
        properties:
          login_banner:
            text: |
              Authorized Use Only.
              Unauthorized use will be prosecuted to the fullest extent of the law.
      - name: user_add
        release: os-conf
        properties:
          persistent_homes: true
          users:
            - name: ((SSH_USERNAME))
              public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbss5XtLYRYDeV8AmouVYOHmYPxPsN4F59fZnY4kJnimM3sk5TbP0ow19GMDppQOPzAQ1TcYH4sYhpnxwq5f32XYtw12rFnO8BatHISWIdjoEjHfdA1qLIMGouWZPbGIQ1qURbfJdR9e2shS7U/WSXD+AJ9Zy0ZKTsIvlukWSX8Nsxvfn7VaAFvhgI3YPmhjV3TCEVMDsWGbBXlMq+qiJt22JEOw+3dnrvfGzRUULGznO/8y4NvVQsQc5KGnJkeQWkmlOIrhUGYwd/hMn6zQEIxkR4elmwp+pjyLR0qYLUFjpMn2GJMG7lvTzF8SzQLhzTVrjW1E3nve2eCuJ5bB6/"
              shell: /bin/zsh # OPTIONAL: Defaults to `/bin/bash`
              sudo: false # OPTIONAL: Defaults to `true`