releases:
  - name: os-conf
    version: 22.0.0

addons:
  - name: os-configuration
    jobs:
      - name: login_banner
        release: os-conf
        properties:
          login_banner:
            text: |
              Authorized Use Only.
              Unauthorized use will be prosecuted to the fullest extent of the law.
