---
common-tags: &common-tags
  - platform-automation
#@ opsman_versions = [ "2.10", "3.0", "3.1"]
#@ pat_versions = ["5.2", "5.3"]
resource_types:
- name: pivnet
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.url))/pivotalcf/pivnet-resource
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
    tag: latest-final
resources:
  - name: weekly
    type: time
    source:
      interval: 168h
      location: America/Denver
      start: 4:00 AM
      stop: 11:00 AM

#@ for pat_version in pat_versions:
  - name: #@ "platform-automation-tasks-" + pat_version
    type: pivnet
    source:
      api_token: ((platform-automation/main.pivnet_token))
      product_slug: platform-automation
      product_version: #@ "^" + pat_version.replace('.', '\.') + "\.\d+$"

  - name: #@ "platform-automation-image-" + pat_version
    type: pivnet
    source:
      api_token: ((platform-automation/main.pivnet_token))
      product_slug: platform-automation
      product_version: #@ "^" + pat_version.replace('.', '\.') + "\.\d+$"
#@ end
  - name: paving
    type: git
    source:
      uri: https://github.com/pivotal/paving
      branch: low-privilege

  - name: docs-platform-automation
    type: git
    source:
      uri: https://github.com/pivotal/docs-platform-automation
      branch: fix-support-pipeline

  - name: deployments
    type: git
    source:
      branch: ci-support-epc
      private_key: ((platform-automation/main/platform_automation_deployments_ghe_deploy_key.private_key))
      uri: ((platform-automation/main.platform_automation_deployments_ghe_uri))

#@ for opsman_version in opsman_versions:
  - name: #@ "opsman-image-" + opsman_version
    type: pivnet
    source:
      api_token: ((platform-automation/main.pivnet_token))
      product_slug: ops-manager
      product_version: #@ "^" + opsman_version.replace('.', '\.') + "\.\d+" + ("(\+LTS-T)?" if opsman_version == "3.0" else "") + "$"

  - name: #@ "example-product-" + opsman_version
    type: s3
    source:
      bucket: example-product-pivotal-files
      private: false
      regexp: #@ "^example-product-(" + opsman_version.replace('.', '\.') + ".*)\.pivotal$"
#@ end
  - name: stemcells-ubuntu-xenial
    type: pivnet
    source:
      api_token: ((platform-automation/main.pivnet_token))
      product_slug: stemcells-ubuntu-xenial
      product_version: ^621\..*
  
  - name: stemcells-ubuntu-jammy
    type: pivnet
    source:
      api_token: ((platform-automation/main.pivnet_token))
      product_slug: stemcells-ubuntu-jammy
      product_version: ^1\..*

jobs:
#@ for pat_version in pat_versions:
#@ for opsman_version in opsman_versions:
- name: #@ "test-opsman-" + opsman_version + "-with-pat-version-" + pat_version
  serial: true
  serial_groups: ["install"]
  plan:
  - in_parallel:
    - get: stemcells-ubuntu-xenial
      params:
        globs:
          - '*vsphere*.tgz'
      tags: *common-tags
    #@ if opsman_version == "3.0":
    - get: stemcells-ubuntu-jammy
      params:
        globs:
          - '*vsphere*.tgz'
      tags: *common-tags
    #@ end
    - get: #@ "example-product-" + opsman_version
      tags: *common-tags
    - get: #@ "opsman-image-" + opsman_version
      tags: *common-tags
      params:
        globs:
          - '*vsphere*'
    - get: weekly
      tags: *common-tags
      trigger: true
    - get: paving
      tags: *common-tags
    - get: platform-automation-tasks
      tags: *common-tags
      resource: #@ "platform-automation-tasks-" + pat_version
      params:
        unpack: true
        globs:
        - "*tasks*.zip"
    - get: platform-automation-image
      tags: *common-tags
      resource: #@ "platform-automation-image-" + pat_version
      params:
        unpack: true
        globs:
        - "*image*.tgz"
    - get: deployments
      tags: *common-tags
    - get: docs-platform-automation
      tags: *common-tags
  - task: prepare-tasks-with-secrets
    image: platform-automation-image
    file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
    input_mapping:
      config: deployments
      tasks: platform-automation-tasks
      vars: deployments
    output_mapping:
      tasks: platform-automation-tasks
    params:
      CONFIG_PATHS: config/ci-support-epc/director.yml config/ci-support-epc/ops-manager.yml config/ci-support-epc/auth.yml
      VARS_PATHS: vars/ci-support-epc/terraform-vars.yml
    tags: *common-tags
  - task: create-vm
    file: platform-automation-tasks/tasks/create-vm.yml
    input_mapping:
      image: #@ "opsman-image-" + opsman_version
      state: deployments
      config: deployments
      vars: deployments
    params:
      STATE_FILE: ci-support-epc/state.yml
      OPSMAN_CONFIG_FILE: ci-support-epc/ops-manager.yml
      VARS_FILES: vars/ci-support-epc/terraform-vars.yml
    tags: *common-tags
    image: platform-automation-image
    ensure:
      do:
        - task: state-file
          file: platform-automation-tasks/tasks/make-git-commit.yml
          params:
            GIT_AUTHOR_NAME: platform-automation-bot
            GIT_AUTHOR_EMAIL: ((platform-automation/main.platform-automation-email))
            COMMIT_MESSAGE: #@ "create-vm update state file for support at " + opsman_version
            FILE_SOURCE_PATH: state.yml
            FILE_DESTINATION_PATH: ci-support-epc/state.yml
          input_mapping:
            repository: deployments
            file-source: generated-state
          image: platform-automation-image
          tags: *common-tags
        - put: deployments
          params:
            rebase: true
            repository: repository-commit
          tags: *common-tags
  - task: configure-authentication
    file: platform-automation-tasks/tasks/configure-authentication.yml
    image: platform-automation-image
    attempts: 20
    input_mapping:
      env: deployments
      config: deployments
    params:
      ENV_FILE: ci-support-epc/env.yml
      AUTH_CONFIG_FILE: ci-support-epc/auth.yml
      VARS_FILES: env/ci-support-epc/terraform-vars.yml
    tags: *common-tags
  - task: configure-director
    file: platform-automation-tasks/tasks/configure-director.yml
    image: platform-automation-image
    input_mapping:
      env: deployments
      config: deployments
    params:
      ENV_FILE: ci-support-epc/env.yml
      VARS_FILES: env/ci-support-epc/terraform-vars.yml
      DIRECTOR_CONFIG_FILE: ci-support-epc/director.yml
    tags: *common-tags
  - task: apply-director-changes
    file: platform-automation-tasks/tasks/apply-director-changes.yml
    image: platform-automation-image
    input_mapping:
      env: deployments
    params:
      ENV_FILE: ci-support-epc/env.yml
    tags: *common-tags
  - task: staged-director-config
    file: platform-automation-tasks/tasks/staged-director-config.yml
    image: platform-automation-image
    input_mapping:
      env: deployments
    params:
      ENV_FILE: ci-support-epc/env.yml
    tags: *common-tags
  - task: export-installation
    file: platform-automation-tasks/tasks/export-installation.yml
    image: platform-automation-image
    input_mapping:
      env: deployments
    params:
      ENV_FILE: ci-support-epc/env.yml
    tags: *common-tags
  - task: upload-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-product.yml
    input_mapping:
      env: deployments
      product: #@ "example-product-" + opsman_version
    params:
      ENV_FILE: ci-support-epc/env.yml
    tags: *common-tags
  - task: stage-configure-apply
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-configure-apply.yml
    input_mapping:
      product: #@ "example-product-" + opsman_version
      env: deployments
      config: deployments
      #@ if opsman_version == "3.0":
      stemcell: stemcells-ubuntu-jammy
      #@ end
    params:
      ENV_FILE: ci-support-epc/env.yml
      CONFIG_FILE: ci-support-epc/example-product.yml
      VARS_FILES: env/ci-support-epc/terraform-vars.yml
      ALLOW_PENDING_CHANGES: false
    tags: *common-tags
  - task: delete-installation
    file: platform-automation-tasks/tasks/delete-installation.yml
    image: platform-automation-image
    input_mapping:
      env: deployments
    params:
      ENV_FILE: ci-support-epc/env.yml
    tags: *common-tags
  - task: delete-opsman-vm
    file: platform-automation-tasks/tasks/delete-vm.yml
    input_mapping:
      state: generated-state
      config: deployments
      vars: deployments
    params:
      OPSMAN_CONFIG_FILE: ci-support-epc/ops-manager.yml
      VARS_FILES: vars/ci-support-epc/terraform-vars.yml
    tags: *common-tags
    image: platform-automation-image
    ensure:
      do:
        - task: state-file
          file: platform-automation-tasks/tasks/make-git-commit.yml
          params:
            GIT_AUTHOR_NAME: platform-automation-bot
            GIT_AUTHOR_EMAIL: ((platform-automation/main.platform-automation-email))
            COMMIT_MESSAGE: #@ "delete-vm update state file for support at " + opsman_version
            FILE_SOURCE_PATH: state.yml
            FILE_DESTINATION_PATH: ci-support-epc/state.yml
          input_mapping:
            repository: deployments
            file-source: generated-state
          image: platform-automation-image
          tags: *common-tags
        - put: deployments
          params:
            rebase: true
            repository: repository-commit
          tags: *common-tags
#@ end
#@ end
