---
platform: linux
inputs:
- name: deployments
- name: docs-platform-automation
outputs:
- name: config
- name: env
- name: vars
- name: state
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
params:
  IAAS:
  BOSH_ENV_PREFIX:
run:
  path: docs-platform-automation/ci/tasks/generate-config/task.sh
