---
platform: linux
inputs:
- name: docs-platform-automation
- name: deployments
- name: paving
outputs:
- name: deployments
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: upgrade-terraform-testing
run:
  path: docs-platform-automation/ci/tasks/create-infrastructure/task.sh
