- name: staged-director-config
  plan:
    - aggregate:
        - get: platform-automation-tasks
          params: {unpack: true}
        - get: platform-automation-image
          params: {unpack: true}
        - get: configuration
    - task: interpolate-env-creds
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        PREFIX: '/pipeline/vsphere'
        INTERPOLATION_PATH: ((foundation))/config
        SKIP_MISSING: true
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-configs
    - task: staged-director-config
      image: platform-automation-image
      file: platform-automation-tasks/tasks/staged-director-config.yml
      input_mapping:
        env: interpolated-env
      output_mapping:
        generated-config: configuration/((foundation))/config
      params:
        ENV_FILE: ((foundation))/env/env.yml
    - task: make-commit
      image: platform-automation-image
      file: platform-automation-tasks/tasks/make-git-commit.yml
      input_mapping:
        repository: configuration
        file-source: configuration/((foundation))/config
      output_mapping:
        repository-commit: configuration-commit
      params:
        FILE_SOURCE_PATH: director.yml
        FILE_DESTINATION_PATH: config/((foundation))/director.yml
        GIT_AUTHOR_EMAIL: "git-author-email@example.com"
        GIT_AUTHOR_NAME: "Git Author"
        COMMIT_MESSAGE: "Update director.yml file"
    - put: configuration
      params:
        repository: configuration-commit
        merge: true