# Packer configuration for building Windows Server 2019 VM for vSphere
# Based on: https://techdocs.broadcom.com/us/en/vmware-tanzu/platform/elastic-application-runtime/6-0/eart/create-vsphere-stemcell-automatically.html
#
# This configuration automates Steps 1-3 from the VMware Tanzu documentation:
#   Step 1: Create a Base VM for the BOSH Stemcell
#   Step 2: Configure the Base VM (network settings and Windows updates)
#   Step 3: Creates a template ready for cloning

packer {
  required_version = ">= 1.7.0"
  required_plugins {
    vsphere = {
      source  = "github.com/hashicorp/vsphere"
      version = ">= 1.4.0"
    }
  }
}

# Variable definitions
variable "vcenter_server" {
  type        = string
  description = "vCenter Server FQDN or IP"
}

variable "vcenter_username" {
  type        = string
  description = "vCenter username"
  sensitive   = true
}

variable "vcenter_password" {
  type        = string
  description = "vCenter password"
  sensitive   = true
}

variable "vcenter_insecure_connection" {
  type        = bool
  description = "Allow insecure vCenter connections (self-signed certs)"
  default     = true
}

variable "http_proxy" {
  type        = string
  description = "HTTP proxy URL for vCenter access"
  default     = ""
}

variable "https_proxy" {
  type        = string
  description = "HTTPS proxy URL for vCenter access"
  default     = ""
}

variable "no_proxy" {
  type        = string
  description = "Comma-separated list of hosts that should not use proxy"
  default     = "localhost,127.0.0.1"
}

variable "vcenter_datacenter" {
  type        = string
  description = "vCenter datacenter name"
}

variable "vcenter_cluster" {
  type        = string
  description = "vCenter cluster name (leave empty if using host)"
  default     = ""
}

variable "vcenter_host" {
  type        = string
  description = "vCenter ESXi host name (leave empty if using cluster)"
  default     = ""
}

variable "vcenter_datastore" {
  type        = string
  description = "vCenter datastore name"
}

variable "vcenter_network" {
  type        = string
  description = "vCenter network/port group name"
}

variable "vcenter_folder" {
  type        = string
  description = "vCenter folder path (optional)"
  default     = ""
}

variable "vcenter_resource_pool" {
  type        = string
  description = "vCenter resource pool name (optional)"
  default     = ""
}

variable "vm_name" {
  type        = string
  description = "Temporary VM name during build"
}

variable "vm_cpu_count" {
  type        = number
  description = "Number of CPUs"
  default     = 4
}

variable "vm_memory_mb" {
  type        = number
  description = "Memory in MB"
  default     = 8192
}

variable "vm_disk_size_gb" {
  type        = number
  description = "Disk size in GB"
  default     = 100
}

variable "template_name" {
  type        = string
  description = "Final template name (optional, defaults to VM name)"
  default     = ""
}

variable "iso_path_local" {
  type        = string
  description = "Local path to Windows Server 2019 ISO (Packer will upload)"
  default     = ""
}

variable "iso_path" {
  type        = string
  description = "Datastore path to Windows Server 2019 ISO (e.g., [datastore1]/ISOs/file.iso)"
  default     = ""
}

variable "windows_username" {
  type        = string
  description = "Windows administrator username"
  default     = "Administrator"
}

variable "windows_password" {
  type        = string
  description = "Windows administrator password"
  sensitive   = true
}

variable "static_ip" {
  type        = string
  description = "Static IP address (required for Step 2)"
}

variable "subnet_mask" {
  type        = string
  description = "Subnet mask (e.g., 255.255.255.0)"
}

variable "gateway" {
  type        = string
  description = "Default gateway"
}

variable "dns_servers" {
  type        = list(string)
  description = "DNS servers (at least one required)"
}

variable "vmware_tools_mode" {
  type        = string
  description = "VMware Tools mode: 'upload' or 'attach'"
  default     = "upload"
}

variable "vmware_tools_path" {
  type        = string
  description = "Path to VMware Tools ISO (if mode is 'attach')"
  default     = ""
}

variable "enable_windows_updates" {
  type        = bool
  description = "Enable Windows updates installation"
  default     = true
}

variable "log_level" {
  type        = string
  description = "Logging level for PowerShell scripts (DEBUG, INFO, WARN, ERROR)"
  default     = "INFO"
}

variable "build_timestamp" {
  type        = string
  description = "Build timestamp (generated by build.sh to ensure consistency)"
  default     = ""
}

  # Local variables
locals {
  # Use provided timestamp if available, otherwise generate one
  # This ensures build.sh and Packer use the same timestamp
  timestamp     = var.build_timestamp != "" ? var.build_timestamp : regex_replace(timestamp(), "[- TZ:]", "")
  vm_name_final = "${var.vm_name}-${local.timestamp}"
  
  # ISO paths - vsphere-iso builder requires datastore paths only
  # Format: [datastore-name]/path/to/file.iso
  # Use upload-iso.sh helper script to upload local ISO to datastore first;-    [0] = Windows OS ISO (for booting) - MUST be Windows Server ISO, not VMware Tools ISO
  # [1] = VMware Tools ISO (mounted as additional CD/DVD drive, available as D: or E:)
  # IMPORTANT: iso_path MUST point to Windows Server ISO, not VMware Tools ISO
  # Verify: iso_path should contain "windows" or "server" in the filename
  iso_path_final = var.iso_path != "" ? var.iso_path : ""
  vmware_tools_iso_path = "[] /vmimages/tools-isoimages/windows.iso"  # Standard vSphere Tools ISO path
  
  # Template name - use provided name, or derive from VM name, or use default
  template_name_final = var.template_name != "" ? var.template_name : "${var.vm_name}-template"
  
  # Scripts directory
  scripts_dir = "scripts"
  
  # Template variables for Autounattend.xml (no longer used - build.sh processes with sed)
  # Kept for reference, but Autounattend.xml is now processed by build.sh before Packer runs
  # autounattend_vars = {
  #   Username = var.windows_username
  #   Password = var.windows_password
  # }
  
  # Common PowerShell environment variables
  common_powershell_env = [
    "STATIC_IP=${var.static_ip}",
    "SUBNET_MASK=${var.subnet_mask}",
    "GATEWAY=${var.gateway}",
    "DNS_SERVERS=${join(",", var.dns_servers)}",
    "ENABLE_UPDATES=${var.enable_windows_updates}",
    "LOG_LEVEL=${var.log_level}"
  ]
}

# Build source
source "vsphere-iso" "windows" {
  # vCenter connection
  vcenter_server      = var.vcenter_server
  username            = var.vcenter_username
  password            = var.vcenter_password
  insecure_connection = var.vcenter_insecure_connection

  # Note: Proxy configuration is handled via environment variables in build script
  # Set HTTP_PROXY, HTTPS_PROXY, NO_PROXY environment variables before running packer

  # VM configuration
  vm_name         = local.vm_name_final
  guest_os_type   = "windows9Server64Guest"
  firmware        = "bios"
  CPUs            = var.vm_cpu_count
  cpu_cores       = 1
  RAM             = var.vm_memory_mb
  RAM_reserve_all = false
  
  # Note: cpu_hot_add_enabled and memory_hot_add_enabled are not supported
  # by the vsphere-iso builder. The "unable to retrieve stepping" error is
  # typically a vSphere/ESXi host CPU compatibility issue, not a Packer configuration issue.

  # Disk configuration - LSI Logic SAS for Windows Server 2019
  # This matches the default vSphere controller type that works manually
  disk_controller_type = ["lsilogic-sas"]
  storage {
    disk_size             = var.vm_disk_size_gb * 1024
    disk_thin_provisioned = true
    disk_controller_index = 0
  }

  # Network configuration
  network_adapters {
    network      = var.vcenter_network
    network_card = "vmxnet3"
  }

  # vSphere location
  datacenter = var.vcenter_datacenter
  datastore  = var.vcenter_datastore
  folder     = var.vcenter_folder != "" ? var.vcenter_folder : null

  # Compute resource
  cluster       = var.vcenter_cluster != "" ? var.vcenter_cluster : null
  host          = var.vcenter_host != "" ? var.vcenter_host : null
  resource_pool = var.vcenter_resource_pool != "" ? var.vcenter_resource_pool : null

  # ISO configuration - Only mount Windows OS ISO initially for booting
  # VMware Tools ISO will be mounted later via provisioner after installation completes
  # This avoids boot order confusion when multiple ISOs are attached
  iso_paths = local.iso_path_final != "" ? [
    local.iso_path_final                    # [0] Windows OS ISO (for booting)
  ] : []
  cdrom_type = "ide"

  # Boot configuration - Boot from CD-ROM (Windows OS ISO) first, then disk
  boot_order = "cdrom,disk"
  # Boot wait time - allows Windows Setup to initialize before boot commands
  # Reduced to 10s for faster execution
  boot_wait  = "10s"

  # Note: vmx_data is not supported in vsphere-iso builder
  # Boot delay and floppy connection are handled by the plugin automatically
  # The boot_wait setting provides the delay needed

  # Autounattend.xml injection - FLOPPY METHOD
  # Windows Setup automatically searches for Autounattend.xml in this order:
  # 1. Floppy drive (A:\) - THIS IS WHERE IT FINDS IT
  # 2. CD/DVD drive (D:\ or E:\)
  # 3. USB drives
  # 4. Network locations
  #
  # Note: Windows Setup is case-insensitive, but we use lowercase to match some docs
  # Using processed Autounattend.xml (variables replaced by build.sh with sed before Packer runs)
  # This is simpler and more reliable than Packer's templatefile() function
  floppy_content = {
    "autounattend.xml" = file("${path.root}/http/Autounattend.processed.xml")
  }

  # Boot commands - Handle UI screens with automatic disk configuration
  # With automatic disk configuration, Windows Setup will show:
  # 1. Language selection (may appear before Autounattend.xml is read)
  # 2. Install Now screen
  # 3. License terms (Accept) - FIRST PROMPT
  # 4. Installation type (Custom/Upgrade) - SECOND PROMPT
  # 5. Disk selection screen (select unallocated space, click Next)
  # 6. Installation proceeds
  # Increased wait times to allow screens to fully load before navigation
  boot_command = [
    "<enter><wait>",      # Press Enter to start installation (initial "Press any key" screen)
    "<wait30>",           # Wait for Windows Setup to load and detect Autounattend.xml (increased from 10s)
    "<enter><wait>",      # Press Enter/Next on language selection (if shown)
    "<wait20>",           # Wait for language selection to process (increased from 10s)
    "<enter><wait>",      # Additional Enter if language selection needs confirmation
    "<wait20>",           # Wait for "Install Now" screen (increased from 10s)
    "<enter><wait>",      # Press Enter on "Install Now" button
    "<wait20>",           # Wait for license terms screen (FIRST PROMPT) (increased from 10s)
    "<tab><wait>",        # Tab to "I accept" checkbox
    "<space><wait>",      # Check "I accept the license terms"
    "<tab><tab><wait>",   # Tab to "Next" button
    "<enter><wait>",      # Press Enter/Next to accept license
    "<wait20>",           # Wait for installation type screen (SECOND PROMPT - Custom/Upgrade) (increased from 10s)
    "<enter><wait>",      # Press Enter to select "Custom" installation (default selection)
    "<wait20>",           # Wait for disk selection screen (increased from 10s)
    # Navigate disk selection - with DiskConfiguration, disk should be formatted
    # If "Windows cannot install on this drive" appears, we need to format it
    # Try: Select disk, click "Format" or "New" to create partition
    "<down><wait>",       # Select unallocated space or Disk 0
    "<tab><tab><tab><wait>", # Tab to "Format" or "New" button (if needed)
    "<enter><wait>",      # Press Enter to format/create partition (if format button)
    "<wait10>",           # Wait for format confirmation (increased from 5s)
    "<enter><wait>",      # Confirm format (if confirmation dialog)
    "<wait20>",           # Wait for partition to be created/formatted (increased from 10s)
    "<tab><tab><wait>",   # Tab to "Next" button
    "<enter><wait>",      # Press Enter/Next to proceed with installation
    "<wait120>"           # Wait for installation to proceed (disk formatting and file copying) (increased from 60s)
  ]

  # Shutdown configuration
  shutdown_command = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  shutdown_timeout = "15m"

  # WinRM configuration
  # Network is configured in Autounattend.xml specialize pass (static IP)
  # After first restart, network is configured and WinRM can connect
  # Packer needs to wait for the static IP to be configured
  communicator   = "winrm"
  winrm_username = var.windows_username
  winrm_password = var.windows_password
  winrm_timeout  = "90m"
  winrm_insecure = true
  winrm_use_ssl  = false
  winrm_port     = 5985

  # IP wait configuration
  # Network is configured in Autounattend.xml specialize pass (static IP)
  # Packer needs to wait for the static IP to be configured after first restart
  # Without DHCP, Packer must wait for the static IP configured in specialize pass
  ip_wait_timeout   = "30m"  # Wait up to 30 minutes for static IP to be configured
  ip_settle_timeout = "2m"   # Wait 2 minutes for IP to settle after configuration

  # Convert to template (Step 3 from documentation)
  convert_to_template = true
}

# Build steps
build {
  name = "windows-vm-build"

  sources = ["source.vsphere-iso.windows"]

  # Step 1: Wait for Windows to be ready (using govc)
  # This waits for WinRM to be available after first restart
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}"
    ]
    command = "${local.scripts_dir}/run-powershell-via-govc.sh '${local.vm_name_final}' '${local.scripts_dir}/01-wait-for-ready.ps1'"
  }

  # Step 1.5: Mount VMware Tools ISO (per documentation)
  # This happens AFTER first restart, when WinRM is available
  # Mounting before first restart can interfere with Windows installation and password reset
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}"
    ]
    command = "${local.scripts_dir}/mount-vmware-tools.sh '${local.vm_name_final}'"
  }

  # Step 1.6: Install VMware Tools (per documentation: run D:\setup64.exe)
  # This happens AFTER Tools ISO is mounted, after first restart
  # The PowerShell script checks if Tools is already installed and skips if so
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}"
    ]
    command = "${local.scripts_dir}/run-powershell-via-govc.sh '${local.vm_name_final}' '${local.scripts_dir}/03-install-vmware-tools.ps1'"
  }

  # Step 2: Configure network using sconfig (per tech doc)
  # Network configuration is done after VMware Tools is mounted and installed
  # This uses PowerShell cmdlets (sconfig is interactive, so we use equivalent PowerShell)
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}",
      "STATIC_IP=${var.static_ip}",
      "SUBNET_MASK=${var.subnet_mask}",
      "GATEWAY=${var.gateway}",
      "DNS_SERVERS=${join(",", var.dns_servers)}",
      "LOG_LEVEL=${var.log_level}"
    ]
    command = "${local.scripts_dir}/run-powershell-via-govc.sh '${local.vm_name_final}' '${local.scripts_dir}/02-configure-network-sconfig.ps1'"
  }

  # Step 2: Install Windows updates (using govc - network now configured via sconfig)
  # Script handles enable_windows_updates flag internally
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}",
      "STATIC_IP=${var.static_ip}",
      "SUBNET_MASK=${var.subnet_mask}",
      "GATEWAY=${var.gateway}",
      "DNS_SERVERS=${join(",", var.dns_servers)}",
      "ENABLE_UPDATES=${var.enable_windows_updates}",
      "LOG_LEVEL=${var.log_level}"
    ]
    command = "${local.scripts_dir}/run-powershell-via-govc.sh '${local.vm_name_final}' '${local.scripts_dir}/04-install-windows-updates.ps1'"
  }


  # Step 1: Disconnect CD/DVD drive (per documentation)
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}"
    ]
    command = "${local.scripts_dir}/eject-cdrom.sh '${local.vm_name_final}'"
  }

  # Step 3: Rename template (if custom name provided)
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}"
    ]
    command = "${local.scripts_dir}/rename-template.sh '${local.vm_name_final}' '${local.template_name_final}'"
  }

  # Final cleanup (using govc)
  provisioner "shell-local" {
    environment_vars = [
      "GOVC_URL=${var.vcenter_server}",
      "GOVC_USERNAME=${var.vcenter_username}",
      "GOVC_PASSWORD=${var.vcenter_password}",
      "GOVC_INSECURE=${var.vcenter_insecure_connection}",
      "LOG_LEVEL=${var.log_level}"
    ]
    command = "${local.scripts_dir}/run-powershell-via-govc.sh '${local.vm_name_final}' '${local.scripts_dir}/06-final-cleanup.ps1'"
  }
}
