# Packer configuration for building Windows Server 2019 VM for vSphere
# Based on: https://techdocs.broadcom.com/us/en/vmware-tanzu/platform/elastic-application-runtime/6-0/eart/create-vsphere-stemcell-automatically.html
#
# This configuration automates Steps 1-3 from the VMware Tanzu documentation:
#   Step 1: Create a Base VM for the BOSH Stemcell
#   Step 2: Configure the Base VM (network settings and Windows updates)
#   Step 3: Creates a template ready for cloning

packer {
  required_version = ">= 1.7.0"
  required_plugins {
    vsphere = {
      source  = "github.com/hashicorp/vsphere"
      version = ">= 1.4.0"
    }
  }
}

# Variable definitions
variable "vcenter_server" {
  type        = string
  description = "vCenter Server FQDN or IP"
}

variable "vcenter_username" {
  type        = string
  description = "vCenter username"
  sensitive   = true
}

variable "vcenter_password" {
  type        = string
  description = "vCenter password"
  sensitive   = true
}

variable "vcenter_insecure_connection" {
  type        = bool
  description = "Allow insecure vCenter connections (self-signed certs)"
  default     = true
}

variable "http_proxy" {
  type        = string
  description = "HTTP proxy URL for vCenter access"
  default     = ""
}

variable "https_proxy" {
  type        = string
  description = "HTTPS proxy URL for vCenter access"
  default     = ""
}

variable "no_proxy" {
  type        = string
  description = "Comma-separated list of hosts that should not use proxy"
  default     = "localhost,127.0.0.1"
}

variable "vcenter_datacenter" {
  type        = string
  description = "vCenter datacenter name"
}

variable "vcenter_cluster" {
  type        = string
  description = "vCenter cluster name (leave empty if using host)"
  default     = ""
}

variable "vcenter_host" {
  type        = string
  description = "vCenter ESXi host name (leave empty if using cluster)"
  default     = ""
}

variable "vcenter_datastore" {
  type        = string
  description = "vCenter datastore name"
}

variable "vcenter_network" {
  type        = string
  description = "vCenter network/port group name"
}

variable "vcenter_folder" {
  type        = string
  description = "vCenter folder path (optional)"
  default     = ""
}

variable "vcenter_resource_pool" {
  type        = string
  description = "vCenter resource pool name (optional)"
  default     = ""
}

variable "vm_name" {
  type        = string
  description = "Temporary VM name during build"
}

variable "vm_cpu_count" {
  type        = number
  description = "Number of CPUs"
  default     = 4
}

variable "vm_memory_mb" {
  type        = number
  description = "Memory in MB"
  default     = 8192
}

variable "vm_disk_size_gb" {
  type        = number
  description = "Disk size in GB"
  default     = 100
}

variable "template_name" {
  type        = string
  description = "Final template name (optional, defaults to VM name)"
  default     = ""
}

variable "iso_path_local" {
  type        = string
  description = "Local path to Windows Server 2019 ISO (Packer will upload)"
  default     = ""
}

variable "iso_path" {
  type        = string
  description = "Datastore path to Windows Server 2019 ISO (e.g., [datastore1]/ISOs/file.iso)"
  default     = ""
}

variable "windows_username" {
  type        = string
  description = "Windows administrator username"
  default     = "Administrator"
}

variable "windows_password" {
  type        = string
  description = "Windows administrator password"
  sensitive   = true
}

variable "static_ip" {
  type        = string
  description = "Static IP address (required for Step 2)"
}

variable "subnet_mask" {
  type        = string
  description = "Subnet mask (e.g., 255.255.255.0)"
}

variable "gateway" {
  type        = string
  description = "Default gateway"
}

variable "dns_servers" {
  type        = list(string)
  description = "DNS servers (at least one required)"
}

variable "vmware_tools_mode" {
  type        = string
  description = "VMware Tools mode: 'upload' or 'attach'"
  default     = "upload"
}

variable "vmware_tools_path" {
  type        = string
  description = "Path to VMware Tools ISO (if mode is 'attach')"
  default     = ""
}

variable "enable_windows_updates" {
  type        = bool
  description = "Enable Windows updates installation"
  default     = true
}

variable "log_level" {
  type        = string
  description = "Logging level for PowerShell scripts (DEBUG, INFO, WARN, ERROR)"
  default     = "INFO"
}

variable "build_timestamp" {
  type        = string
  description = "Build timestamp (generated by build.sh to ensure consistency)"
  default     = ""
}

variable "template_path" {
  type        = string
  description = "vCenter inventory path to source template (e.g., /Datacenter/vm/Templates/my-template). If provided, VM will be cloned from template instead of installing from ISO"
  default     = ""
}

  # Local variables
locals {
  # Use provided timestamp if available, otherwise generate one
  # This ensures build.sh and Packer use the same timestamp
  timestamp     = var.build_timestamp != "" ? var.build_timestamp : regex_replace(timestamp(), "[- TZ:]", "")
  vm_name_final = "${var.vm_name}-${local.timestamp}"
  
  # Build mode detection: template mode if template_path is provided and no ISO is configured
  # ISO mode if ISO is configured (template_path can still be used to create template after stemcell)
  is_template_mode = var.template_path != "" && var.iso_path == "" && var.iso_path_local == ""
  
  # ISO paths - vsphere-iso builder requires datastore paths only
  # Format: [datastore-name]/path/to/file.iso
  # Use upload-iso.sh helper script to upload local ISO to datastore first
  # IMPORTANT: iso_path MUST point to Windows Server ISO, not VMware Tools ISO
  # Verify: iso_path should contain "windows" or "server" in the filename
  iso_path_final = var.iso_path != "" ? var.iso_path : ""
  
  # Template name - use provided name, or derive from VM name, or use default
  template_name_final = var.template_name != "" ? var.template_name : "${var.vm_name}-template"
  
  # Scripts directory
  scripts_dir = "scripts"
  
  # Common PowerShell environment variables
  common_powershell_env = [
    "STATIC_IP=${var.static_ip}",
    "SUBNET_MASK=${var.subnet_mask}",
    "GATEWAY=${var.gateway}",
    "DNS_SERVERS=${join(",", var.dns_servers)}",
    "ENABLE_UPDATES=${var.enable_windows_updates}",
    "LOG_LEVEL=${var.log_level}"
  ]
}

# Build source for ISO mode (installing from Windows ISO)
source "vsphere-iso" "windows" {
  # vCenter connection
  vcenter_server      = var.vcenter_server
  username            = var.vcenter_username
  password            = var.vcenter_password
  insecure_connection = var.vcenter_insecure_connection

  # Note: Proxy configuration is handled via environment variables in build script
  # Set HTTP_PROXY, HTTPS_PROXY, NO_PROXY environment variables before running packer

  # VM configuration
  vm_name         = local.vm_name_final
  guest_os_type   = "windows9Server64Guest"
  firmware        = "bios"
  CPUs            = var.vm_cpu_count
  cpu_cores       = 1
  RAM             = var.vm_memory_mb
  RAM_reserve_all = false
  
  # Note: cpu_hot_add_enabled and memory_hot_add_enabled are not supported
  # by the vsphere-iso builder. The "unable to retrieve stepping" error is
  # typically a vSphere/ESXi host CPU compatibility issue, not a Packer configuration issue.

  # Disk configuration - LSI Logic SAS for Windows Server 2019
  # This matches the default vSphere controller type that works manually
  disk_controller_type = ["lsilogic-sas"]
  storage {
    disk_size             = var.vm_disk_size_gb * 1024
    disk_thin_provisioned = true
    disk_controller_index = 0
  }

  # Network configuration
  network_adapters {
    network      = var.vcenter_network
    network_card = "vmxnet3"
  }

  # vSphere location
  datacenter = var.vcenter_datacenter
  datastore  = var.vcenter_datastore
  folder     = var.vcenter_folder != "" ? var.vcenter_folder : null

  # Compute resource
  cluster       = var.vcenter_cluster != "" ? var.vcenter_cluster : null
  host          = var.vcenter_host != "" ? var.vcenter_host : null
  resource_pool = var.vcenter_resource_pool != "" ? var.vcenter_resource_pool : null

  # ISO configuration - Only mount Windows OS ISO initially for booting
  # VMware Tools ISO will be mounted later via provisioner after installation completes
  # This avoids boot order confusion when multiple ISOs are attached
  # IMPORTANT: iso_path must be set via PKR_VAR_iso_path environment variable or -var flag
  # If iso_paths is empty, the VM will start without an ISO and installation will fail
  # ISO path format: [datastore-name]/path/to/file.iso (must match exactly, case-sensitive)
  iso_paths = local.iso_path_final != "" ? [
    local.iso_path_final                    # [0] Windows OS ISO (for booting)
  ] : []
  
  # CD-ROM type: "ide" for BIOS firmware, "sata" for UEFI firmware
  # Windows Server 2019 with BIOS firmware uses IDE CD-ROM
  cdrom_type = "ide"
  
  # Ensure CD-ROM is connected at boot
  # The vsphere-iso builder should handle this automatically, but we can verify
  # Note: There's no explicit "connect_cdrom" option in vsphere-iso builder
  # The ISO should be automatically connected when iso_paths is set
  
  # Validate ISO path is set (this will cause a clear error if not set)
  # Note: We can't use validation blocks in source blocks, so we rely on the conditional above

  # Boot configuration - Boot from CD-ROM (Windows OS ISO) first, then disk
  boot_order = "cdrom,disk"
  # Boot wait time - allows Windows Setup to initialize before boot commands
  boot_wait  = "10s"

  # Autounattend.xml injection - FLOPPY METHOD
  # Windows Setup automatically searches for Autounattend.xml in this order:
  # 1. Floppy drive (A:\) - THIS IS WHERE IT FINDS IT
  # 2. CD/DVD drive (D:\ or E:\)
  # 3. USB drives
  # 4. Network locations
  #
  # Note: Windows Setup is case-insensitive, but we use lowercase to match some docs
  # Using processed Autounattend.xml (variables replaced by build.sh with sed before Packer runs)
  # This is simpler and more reliable than Packer's templatefile() function
  floppy_content = {
    "autounattend.xml" = file("${path.root}/http/Autounattend.processed.xml")
  }

  # Boot commands - Handle UI screens with automatic disk configuration
  # With automatic disk configuration, Windows Setup will show:
  # 1. Language selection (may appear before Autounattend.xml is read)
  # 2. Install Now screen
  # 3. License terms (Accept) - FIRST PROMPT
  # 4. Installation type (Custom/Upgrade) - SECOND PROMPT
  # 5. Disk selection screen (select unallocated space, click Next)
  # 6. Installation proceeds
  # Increased wait times to allow screens to fully load before navigation
  boot_command = [
    "<enter><wait>",      # Press Enter to start installation (initial "Press any key" screen)
    "<wait60>",           # Wait for Windows Setup to load and detect Autounattend.xml (increased to 60s to ensure Autounattend.xml is read)
    # Language selection screen - explicitly select English (US)
    # If language selection screen appears, we need to navigate to English (US)
    # Default might be Spanish Argentina or other locale, so we explicitly select English
    "<down><wait>",       # Navigate down to find English (US) if not at top
    "<down><wait>",       # Continue navigating if needed
    "<up><wait>",         # Navigate up to English (US) - typically at top of list
    "<up><wait>",         # Ensure we're at English (US)
    "<enter><wait>",      # Press Enter to select English (US) language
    "<wait20>",           # Wait for language selection to process (increased from 10s)
    "<enter><wait>",      # Press Enter/Next to confirm language selection
    "<wait20>",           # Wait for "Install Now" screen (increased from 10s)
    "<enter><wait>",      # Press Enter on "Install Now" button
    "<wait20>",           # Wait for license terms screen (FIRST PROMPT) (increased from 10s)
    "<tab><wait>",        # Tab to "I accept" checkbox
    "<space><wait>",      # Check "I accept the license terms"
    "<tab><tab><wait>",   # Tab to "Next" button
    "<enter><wait>",      # Press Enter/Next to accept license
    "<wait20>",           # Wait for installation type screen (SECOND PROMPT - Custom/Upgrade) (increased from 10s)
    "<enter><wait>",      # Press Enter to select "Custom" installation (default selection)
    "<wait20>",           # Wait for disk selection screen (increased from 10s)
    # Navigate disk selection - with DiskConfiguration, disk should be formatted
    # If "Windows cannot install on this drive" appears, we need to format it
    # Try: Select disk, click "Format" or "New" to create partition
    "<down><wait>",       # Select unallocated space or Disk 0
    "<tab><tab><tab><wait>", # Tab to "Format" or "New" button (if needed)
    "<enter><wait>",      # Press Enter to format/create partition (if format button)
    "<wait10>",           # Wait for format confirmation (increased from 5s)
    "<enter><wait>",      # Confirm format (if confirmation dialog)
    "<wait20>",           # Wait for partition to be created/formatted (increased from 10s)
    "<tab><tab><wait>",   # Tab to "Next" button
    "<enter><wait>",      # Press Enter/Next to proceed with installation
    "<wait120>",          # Wait for installation to proceed (disk formatting and file copying)
    # After installation, Windows will reboot automatically
    # Password change is handled post-build in build.sh via govc keystrokes
    "<wait60>"            # Wait for Windows to boot after installation (first boot after reboot)
  ]

  # Communicator configuration - DISABLED
  # All provisioners are shell-local and use govc (not WinRM)
  # govc commands work at the vSphere API level and don't require:
  #   - IP address assignment
  #   - WinRM connectivity
  #   - Guest OS login
  # Setting communicator to "none" completely disables IP wait and communicator wait
  # This allows shell-local provisioners to run immediately after boot commands
  communicator = "none"

  # Shutdown configuration - DISABLED
  # We handle shutdown via govc in build.sh post-build provisioning
  # Setting a very long shutdown timeout so Packer doesn't try to shutdown before post-build completes
  # Post-build provisioning can take 20-30 minutes (installation wait + password change + Tools + updates)
  # We set timeout to 2 hours to ensure Packer doesn't interfere
  # Note: Packer will timeout on shutdown, but that's expected - build.sh handles shutdown
  shutdown_timeout = "2h"

  # VM cleanup and template conversion - DISABLED
  # We handle shutdown and template conversion via govc in build.sh
  # This prevents Packer from deleting VM on communicator failure
  # Note: vsphere-iso builder doesn't have skip_clean_vm option
  # We'll handle everything post-build in build.sh to keep VM even on failure
  convert_to_template = false  # We'll convert via govc in build.sh
}

# Build source for template mode (cloning from existing template)
source "vsphere-clone" "windows-template" {
  # vCenter connection
  vcenter_server      = var.vcenter_server
  username            = var.vcenter_username
  password            = var.vcenter_password
  insecure_connection = var.vcenter_insecure_connection

  # Template configuration
  template      = var.template_path
  vm_name       = local.vm_name_final
  datacenter    = var.vcenter_datacenter
  datastore     = var.vcenter_datastore
  folder        = var.vcenter_folder != "" ? var.vcenter_folder : null
  cluster       = var.vcenter_cluster != "" ? var.vcenter_cluster : null
  host          = var.vcenter_host != "" ? var.vcenter_host : null
  resource_pool = var.vcenter_resource_pool != "" ? var.vcenter_resource_pool : null

  # VM configuration (can override template settings)
  CPUs            = var.vm_cpu_count
  cpu_cores       = 1
  RAM             = var.vm_memory_mb
  RAM_reserve_all = false

  # Disk configuration
  disk {
    disk_size             = var.vm_disk_size_gb * 1024
    disk_thin_provisioned = true
  }

  # Network configuration
  network_adapters {
    network      = var.vcenter_network
    network_card = "vmxnet3"
  }

  # Communicator configuration - DISABLED
  # All provisioners are shell-local and use govc (not WinRM)
  communicator = "none"

  # Shutdown configuration
  # We handle shutdown via govc in build.sh post-build provisioning
  shutdown_timeout = "2h"

  # VM cleanup - DISABLED
  # We handle shutdown and deletion via govc in build.sh
  # Template mode: Always delete VM after build (success or failure)
  convert_to_template = false
}

# Build steps
# Conditionally use ISO or template source based on template_path variable
build {
  name = "windows-vm-build"

  # Conditionally select source based on build mode
  dynamic "sources" {
    for_each = local.is_template_mode ? ["template"] : ["iso"]
    content {
      source = sources.value == "template" ? "source.vsphere-clone.windows-template" : "source.vsphere-iso.windows"
    }
  }

  # Minimal provisioner to signal Packer that build is complete
  # This allows Packer to exit immediately without waiting for shutdown
  # VM remains running, and build.sh handles all post-build provisioning
  provisioner "shell-local" {
    inline = [
      "echo 'Packer build complete - VM remains running'",
      "echo 'Build mode: ${local.is_template_mode ? "template" : "iso"}'"
    ]
  }
}
