---
platform: linux
inputs:
- name: docs-platform-automation
- name: deployments
- name: paving
outputs:
- name: deployments
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
params:
  IAAS:
run:
  path: docs-platform-automation/ci/tasks/delete-infrastructure/task.sh
