<div class="mermaid">
graph TD;
  versionChk[Is the existingOperations Manager version less than theOperations Manager image?];
  versionError[Version Check Error];
  delete[Delete the existingOperations Manager VM];
  create[Create a newOperations Manager VM];
  iaasErr[IAAS CLI error];
  import[Import the provided Installation];
  iaasErr2[IAAS CLI error];
  versionChk -- No --> versionError;
  versionChk -- Yes --> delete;
  delete -- Success --> create;
  delete -- Failure --> iaasErr;
  create -- Success --> import ;
  create -- Failure --> iaasErr2;
</div>