---
platform: linux
inputs:
- name: generated-state
- name: deployments
- name: docs-platform-automation
outputs:
- name: deployments-updated
image_resource:
  type: registry-image
  source:
    repository: ((docker.ci-repository))
    tag: testing
params:
  IAAS:
run:
  path: docs-platform-automation/ci/tasks/make-commit/task.sh
