---
platform: linux
inputs:
- name: generated-state
- name: deployments
- name: docs-platform-automation
outputs:
- name: deployments-updated
image_resource:
  type: registry-image
  source:
    repository: ((concourse-team/dev_image_registry.dev_url))/internalpcfplatformautomation/ci
    tag: testing
    username: ((concourse-team/dev_image_registry.username))
    password: ((concourse-team/dev_image_registry.password))
params:
  IAAS:
run:
  path: docs-platform-automation/ci/tasks/make-commit/task.sh
